add lesson4
mk17ru/Kotlin-Tinkoff pull request #5
Opened 2021-03-08 17:16 UTC by mk17ru

2021-03-16 16:29 UTC, eld0727 requested changes

2021-03-16 16:29 UTC, eld0727 commented on lesson4/src/main/kotlin/Posts.kt
> +class Posts {
Лучше это обозвать как то, чтобы оно соотвествовало названию класса, который предоставляет данные

- PostsDAO
- PostsRepository
- PostsSerivce

2021-03-16 16:29 UTC, eld0727 commented on lesson4/src/main/kotlin/Users.kt
> +class Users {
Лучше это обозвать как то, чтобы оно соотвествовало названию класса, который предоставляет данные

- UsersDAO
- UsersRepository
- UsersSerivce

2021-03-16 16:29 UTC, eld0727 commented on lesson4/src/main/kotlin/Application.kt
> +    println("1 Task")
Все вот эти методы необходимо реализовать в каком то сервисе, куда ты в конструкторе передашь источники данных постов и пользователей.

2021-03-16 20:20 UTC, mk17ru commented on lesson4/src/main/kotlin/Application.kt
> +    println("1 Task")
Исправил @eld0727

2021-03-17 13:17 UTC, eld0727 commented on lesson4/src/main/kotlin/Server.kt
> +    fun countFullUsersWithoutPosts() : Int {
> Метод, возвращающий количество элементов списка из 5а соответствующих переданному условию, должен принимать на вход предикат.

Вот это условие не выполнено

2021-03-22 18:27 UTC, merged